# Configuration file for Scale_IRFs.py code.
general:
    caldb: '1dc'
    irf: 'South_z20_50h'
    output_irf_name: "my_South_z20_50h"
    # The name of the output IRF file, e.g. 'irf_scaled_version.fits' (the name must follow
    # the "irf_*.fits" template). The file will be put to the main directory of the chosen IRF.
    output_irf_file_name: "irf_scaled_version.fits"

# Aeff specific
aeff:
    # Energy scaling
    energy_scaling:
        # Choices: 'constant', 'gradient', 'step'
        err_func_type: 'step'
        constant:
            scale: 1.0
        gradient:
            scale: 0.1
            range_min: 0.02  # TeV
            range_max: 100.0  # TeV
        step:
            scale: 0.1
            # Transition energies in TeV
            transition_pos: [0.15, 5.0]
            # Log10 transition widths (to be determined from IRF)
            transition_widths: [0.11, 0.06]

    # Angular scaling
    angular_scaling:
        # Choices: 'constant', 'gradient', 'step'
        err_func_type: 'step'
        constant:
            scale: 1.0
        gradient:
            scale: 0.1
            range_min: 0.0  # deg
            range_max: 7.6  # deg
        step:
            scale: 0.05
            transition_pos: [4.3, 7.6]  # deg
            transition_widths: [0.1, 0.1]  # deg

# PSF specific
psf:
    # Choices: 'constant'
    err_func_type: 'constant'
    constant:
        scale: 1.00  # relative factors. 1 means no scaling.
